### ISSUE TITLE
will it work for model HINK-E029A01?

### ISSUE THREAD

**Issue by shark526** [mcer12/GxEPD_HINKE029A10_plugin#1]
thanks for this plugin, but I just got a model HINK-E029A01, will this also work or need some change as well?
got the specification here: https://www.texim-europe.com/getfile.aspx?id=108185#pdfjs.action=download
could you please advise?
thanks

**Comment by mcer12** [comment]
From a quick glance it seems like it's a monochromatic display. That should work with the stock GxEPD. Try both GxEPD and GxEPD2, some displays work with one and not the other and vice versa. Try the 2.9" options in there, one of them should work for you ;) if I'm wrong and it's in fact a 3-color display, feel free to try this plugin, in the worst case it won't work.

**Comment by mcer12** [comment]
@shark526 two years later so if anyone stumbles upon this :D I got to try the display and it works with this plugin, just bear in mind that it will be slower (it waits for the non-existent red color). I suggest to use GxEPD2 (GxEPD2_290_T94) which should be slightly faster. These HINK displays seem to be shitty and slow so don't expect miracles.
